[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/kalender"
  to = "/.netlify/functions/kalender"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/logo"
  to = "/.netlify/functions/logo"
  status = 200

[[redirects]]
  from = "/klassement"
  to = "/.netlify/functions/klassement"
  status = 200

[[redirects]]
  from = "/poging"
  to = "/.netlify/functions/poging"
  status = 200
